name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_mlkit_text_recognition: ^0.12.1
  gallery_picker: ^0.5.1
  image_picker: ^1.1.0
  url_launcher: ^6.0.20
  csv: ^5.0.0
  share: ^2.0.4
  path_provider: ^2.0.14

  google_ml_kit: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true